export { default as Sidebar } from './Sidebar/index.vue'
export { default as Settings } from './Settings/index.vue'
export { default as TagsView } from './TagsView/index.vue'
export { default as NavBar } from './NavBar.vue'
export { default as AppMain } from './AppMain.vue'
